### ISSUE TITLE
DELETE EVENT DOES NOT WORK 

### ISSUE THREAD

**Issue by ahmedtm9** [googleapis/python-recommendations-ai#12]
```py
import google.cloud.recommendationengine as ai2
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "{SERVICE ACCOUNT}"

client2= ai2.UserEventServiceClient()
client = ai2.PurgeUserEventsRequest(parent='projects/{PROJECT_ID}/locations/global/catalogs/default_catalog/eventStores/default_event_store', filter='visitorId="visitor1024"' , force=True)

ex=client2.purge_user_events(request=client)
print(ex.result())
```
-------------------------------------------------------
```py
Traceback (most recent call last):
  File "/Users/ahmedmohamed/PycharmProjects/rec-ai/venv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/ahmedmohamed/PycharmProjects/rec-ai/venv/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/ahmedmohamed/PycharmProjects/rec-ai/venv/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Resource name purge-userevents-default_catalog-default_event_store-983524372863546624 cannot be parsed. Resource name prefix must be of the format 'v1beta1/projects/<Your_Project_Number>/locations/*/catalogs/*/eventStores/*/operations/*'. Make sure to pass Project Number instead of Project ID. To get the Project number, refer to https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects"
	debug_error_string = "{"created":"@1600259736.735677000","description":"Error received from peer ipv6:[2a00:1450:4009:811::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Resource name purge-userevents-default_catalog-default_event_store-983524372863546624 cannot be parsed. Resource name prefix must be of the format 'v1beta1/projects/<Your_Project_Number>/locations/*/catalogs/*/eventStores/*/operations/*'. Make sure to pass Project Number instead of Project ID. To get the Project number, refer to https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects","grpc_status":3}"
```

**Comment by busunkim96** [comment]
Hi @ahmedtm9,

It looks like this API requires a project number. You can follow the link provided below to determine the project number.


> Resource name purge-userevents-default_catalog-default_event_store-983524372863546624 cannot be parsed. Resource name prefix must be of the format 'v1beta1/projects/<Your_Project_Number>/locations/*/catalogs/*/eventStores/*/operations/*'. Make sure to pass Project Number instead of Project ID. To get the Project number, refer to https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects

That said, I believe most APIs support both project IDs and project numbers. I'll follow up with the service team.

**Comment by ahmedtm9** [comment]
Hi @busunkim96,

I have tried using project number and have also tried using project ID, the error is still the same. I did not put them in the code above for privacy.

Thanks,
Ahmed

**Comment by busunkim96** [comment]
It doesn't look like the resource name in the error message `purge-userevents-default_catalog-default_event_store-983524372863546624`follows the expected pattern. Was that also edited?

https://github.com/googleapis/python-recommendations-ai/blob/90a06d1edb5b72403c6e039f99c90d1bdeef3337/google/cloud/recommendationengine_v1beta1/types/user_event_service.py#L46

**Comment by ahmedtm9** [comment]
No it was not edited so that is the raw error, each time the script was run, I had the same error ending with a different random number.
purge-userevents-default_catalog-default_event_store-RANDOM

**Comment by busunkim96** [comment]
Alright, I think we'll have to route this to the service team.

Did this work previously, or have you been consistently seeing this error?

**Comment by ahmedtm9** [comment]
Thanks for your prompt response, no I have seeing this consistently. It would be really helpful if the service team can quickly help with this as I have the recommender broken in production.

**Comment by busunkim96** [comment]
The service team has confirmed the issue and is working on solutions.

@ahmedtm9 If you have a support contract with Google, make sure to open a case: https://cloud.google.com/support

**Comment by ahmedtm9** [comment]
@busunkim96 

Thanks for updating. I figure out an alternative solution which sending POST request using python. It could help others meanwhile

import requests
import json
from google.oauth2 import service_account
from oauth2client.service_account import ServiceAccountCredentials
# The scope for the OAuth2 request.
SCOPE = 'https://www.googleapis.com/auth/cloud-platform'
# The location of the key file with the key data.
KEY_FILEPATH = {SERVICE ACCOUNT KEY PATH} 

# Defines a method to get an access token from the ServiceAccount object.
def get_access_token():
    return ServiceAccountCredentials.from_json_keyfile_name(
      KEY_FILEPATH, SCOPE).get_access_token().access_token

r  = requests.post('https://recommendationengine.googleapis.com/v1beta1/projects/{PROJECT_ID}/locations/global/catalogs/default_catalog/eventStores/default_event_store/userEvents:purge',
    headers={'Authorization': 'Bearer %s' % get_access_token()}, data={'filter': 'eventTime>"2020-09-17T18:25:43.511Z"', 'force': True})

**Comment by nlgtuankiet** [comment]
I'm facing the same issue using both REST API and the client library. The response looking something like
```
curl -X POST -H "Authorization: Bearer "$(gcloud auth print-access-token blabla)"" \
      -H "Content-Type: application/json; charset=utf-8" \
     --data '{
              "filter":"eventTime<\"2020-09-17T18:25:43.511Z\"",
              "force":"false" 
    }' \
    "https://recommendationengine.googleapis.com/v1beta1/projects/blabla/locations/global/catalogs/default_catalog/eventStores/default_event_store/userEvents:purge"
```
```
{
  "name": "purge-userevents-default_catalog-default_event_store-11256037574273429083"
}
```
I think this suppose to list the event that about to be deleted, setting force to true/false or any filter return the same result. 
One workaround is that you have to wipe out all items in the catalog, then your events somehow wiped too.

@busunkim96  Do you know someone on the service team that we can contact with?

**Comment by busunkim96** [comment]
@nlgtuankiet If you have a support contract with google, please open an case. https://cloud.google.com/support/. If not, you can open an issue on the public tracker https://issuetracker.google.com/savedsearches/5808525

**Comment by sterling-swygert** [comment]
Is this still failing? What is the proper response for a successful purge?

**Comment by busunkim96** [comment]
@sterling-swygert This is now resolved, you should be able to call the purge event as shown in the original post without seeing errors.

**Comment by dirkbosman** [comment]
I already tried the v1 here (https://github.com/googleapis/java-recommendations-ai/issues/155#issuecomment-859871828), now after trying v2, I also experienced the same problem with `force => true` enabled :( 

**Step 1:**
#https://cloud.google.com/retail/docs/reference/rest/v2/projects.locations.catalogs.userEvents/purge
#POST https://retail.googleapis.com/v2/{parent=projects/*/locations/*/catalogs/*}/userEvents:purge

After executing above request, the following is printed out sucessfully:

```
{
  "name": "projects/<project-id>/locations/global/catalogs/default_catalog/operations/purge-user-events-<operations-id>"
}
```

**Step 2:** 
https://cloud.google.com/retail/docs/reference/rest/v2/projects.locations.operations/get
#GET https://retail.googleapis.com/v2/{name=projects/*/locations/*/operations/*}

After copying the operation-id above to step 2 and executing, it gives me the same out after the step 1 was executed. So nothing happened...

```
{
  "name": "projects/<project-id>/locations/global/catalogs/default_catalog/operations/purge-user-events-<operations-id>"
}
```

Am I am missing something here? Anybody else out there having this same problem? 

Thanks in advance :)

**Comment by rodfloripa** [comment]
I tried v2, how much time does it take to purge the events? The documentation says that it takes several days to purge.
I tried the status command to see the status of the deletion process, but it only gives me the code of the process:
curl -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
"https://retail.googleapis.com/v2/projects/PROJECT-ID/locations/global/catalogs/default_catalog/operations/purge-user-events-PROCESS-ID"

**Comment by rodfloripa** [comment]
Ok,now it's deleting the events.
It takes 24h to delete events.
